### PR TITLE
add markjam command

### PR DESCRIPTION
**Pull request by DaInfLoop**
wow so cool

### CODE REVIEW

**Comment by lajbel** [comment]
Goooood

**Review by lajbel — APPROVED** [review]

**Review by lajbel — APPROVED** [review]

**Comment by DaInfLoop** [comment]
merge when

**Comment by DaInfLoop** [comment]
oh wait

**Comment by DaInfLoop** [comment]
i draft because theres no code seeing when a option is chosen

**Review by lajbel — APPROVED** [review]

**Comment by DaInfLoop** [comment]
HOLY FRICK

**Pull request merged**
