### PR TITLE
New command: /tag, Edited /hi

### PR DESCRIPTION
**Pull request by DaInfLoop**
# New commands:
`/tag`:
please help i spent way too long on this

> Syntax:
> /tag name(required):{string} code(optional):{string}

Uses replit db.

# Updated commands:
`/hi`
I read deno docs and now fixed it woo hoo me
Will send the nickname for now

### CODE REVIEW

**Comment by DaInfLoop** [comment]
when LaJBel takes their time

**Comment by lajbel** [comment]
time to try with this

**Review by lajbel — APPROVED** [review]

**Comment by DaInfLoop** [comment]
@lajbel re-open pr?

**Comment by lajbel** [comment]
open other

**Pull request merged**
